### ISSUE TITLE
FR: Control LED

### ISSUE THREAD

**Issue by 0-st** [adafruit/Adafruit_CircuitPython_SHT31D#21]
It would be nice to disable the green LED during the night or to only turn it on when the heater is on.

**Comment by jposada202020** [comment]
Not sure this is possible, led light is connected to VCC and GND, please see
https://cdn-learn.adafruit.com/assets/assets/000/101/420/original/adafruit_products_SHT31_sch.png?1618422202

**Comment by 0-st** [comment]
Ok thanks, I desoldered the LED

**Comment by jposada202020** [comment]
:) No problem, I keep it open to see if anyone else wanted to give some feedback :). Thanks
